### ISSUE TITLE
containerize guide

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-containerize#102]
@tt-le commented on [Mon Mar 15 2021](https://github.com/OpenLiberty/cloud-hosted-guides/issues/593)

## step 7

<img width="700" alt="Screen Shot 2021-03-15 at 2 43 55 PM" src="https://user-images.githubusercontent.com/44335153/111204826-dfbc8b00-859c-11eb-8676-2f7f523a9a53.png">

- [x] The command should be `curl http://localhost:**9091**/inventory/systems/{$SYSTEM_IP}`

- [ ] The text before this command tells you to get use the previously found IP, so I think we should either remove ```SYSTEM_IP=`docker inspect -f "{{.NetworkSettings.IPAddress }}" system` ```  from the command or rewrite the instruction

## step 8

- [x] Potentially visual bug? The font size decreases here
<img width="700" alt="Screen Shot 2021-03-15 at 2 48 59 PM" src="https://user-images.githubusercontent.com/44335153/111205408-97519d00-859d-11eb-8597-9f70296d4e54.png">

- [ ] Test failure for inventory
<img width="973" alt="Screen Shot 2021-03-15 at 2 53 44 PM" src="https://user-images.githubusercontent.com/44335153/111206015-3ffffc80-859e-11eb-9716-3265fef71350.png">

**Comment by priyyanshi** [comment]
Could not reproduce the test failure for inventory.

**Comment by gkwan-ibm** [comment]
close
- cannot reproduce the test failure
- no action to 
> remove SYSTEM_IP=`docker inspect -f "{{.NetworkSettings.IPAddress }}" system`
