### ISSUE TITLE
Open Liberty image tag

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/guide-containerize#108]
Regarding this section in the guide:

"In this case, you’re using the recommended production image, openliberty/open-liberty:full-java11-openj9-ubi, as your parent image. If you don’t want any additional runtime features for your kernel image, define the FROM instruction as FROM open-liberty:kernel. To use the default image that comes with the Open Liberty runtime, define the FROM instruction as FROM open-liberty. You can find all the official images and ubi images on the open-liberty Docker Hub."

"kernel" tag was deprecated. "kernel-slim" is the new tag for Open Liberty that provides true kernel image.

"full" tag based images provide all Liberty features and are provided for convenience only. That is not what we should recommend customers use in production. Customers should instead use _kernel-slim_ to start with the bare minimum server and expand it with the necessary features by using the features.sh provided with base image. See usage pattern at https://github.com/OpenLiberty/ci.docker#building-an-application-image

**Comment by leochr** [comment]
cc @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- the guide was updated

**Comment by leochr** [comment]
The second concern is not addressed:

"full" tag based images provide all Liberty features and are provided for convenience only. That is not what we should recommend customers use in production. Customers should instead use kernel-slim to start with the bare minimum server and expand it with the necessary features by using the features.sh provided with base image. See usage pattern at https://github.com/OpenLiberty/ci.docker#building-an-application-image

**Comment by gkwan-ibm** [comment]
similar to the containerize-podman guide

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
