### ISSUE TITLE
Should cover the use of the kernel-slim image and building an optimally-sized image

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-containerize#120]
The guide should cover the use of the kernel-slim image and features.sh to build an optimally-sized image.

@gkwan-ibm, can you please prioritize and work with the team on it?

Cc @leochr

**Comment by yeekangc** [comment]
If appropriate, take the opportunity to cover containers and Containerfile in general vs what is specific to Docker.

**Comment by gkwan-ibm** [comment]
- can add a new section before the [Testing the microservices](https://openliberty.io/guides/containerize.html#testing-the-microservices) section.
  - title, e.g. "Optimizing the image size" 
  - replace the Dockerfile with `icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi` and `RUN features.sh`
  - explain both changes
- doubt to use Containerfile at this moment, should do it to all guides when everything is ready
- containerize-podman guide need to do the same and it uses Containerfile

**Comment by gkwan-ibm** [comment]
close
- the new section was added, visit https://openliberty.io/guides/containerize.html#optimizing-the-image-size and https://openliberty.io/guides/containerize-podman.html#optimizing-the-image-size
