### ISSUE TITLE
The Run in Cloud version of the Containerizing microservices guide has some strange renderings

### ISSUE THREAD

**Issue by cthigh** [OpenLiberty/guide-containerize#128]
See the text "You'  ll" multiple times in this Run in Container mode

![image](https://user-images.githubusercontent.com/17861985/192641956-79c5d425-4a2b-4cb8-bd8c-c795ef4c8842.png)

The "Injecting dependencies into microservices" Run in Container mode has the same issue.
![image](https://user-images.githubusercontent.com/17861985/192643287-098a8733-ab69-4b21-9d0a-6db9a48ddaa0.png)

**Comment by jakub-pomykala** [comment]
Hi @cthigh thank you for opening this issue.

I just had a look and I can't seem to find this in any of our cloud hosted guides; it is possible that this was a temp issue that got fix.

Would you be able to verify this again. I see that you were running the [Containerizing microservices](https://openliberty.io/guides/containerize.html) guide. TYIA

**Comment by cthigh** [comment]
@jakub-pomykala - I tried the Containerizing Microservices guide and no longer see the issue that I saw at JConf in September. Thanks for checking.  Closing this issue.

**Comment by jakub-pomykala** [comment]
Thank you for confirming :)
