### ISSUE TITLE
The Explanation of docker container and how to build and run a docker is so good.

### ISSUE THREAD

**Issue by joniemc** [OpenLiberty/guide-containerize#135]
The Explanation of docker container and how to build and run a docker is so good.

**Comment by gkwan-ibm** [comment]
hi @joniemc  does the [Using Docker containers to develop microservices](https://openliberty.io/guides/docker.html) guide help you to understand "..docker container and how to build and run a docker..."?

**Comment by gkwan-ibm** [comment]
We will consider to add the link of [Using Docker containers to develop microservices](https://openliberty.io/guides/docker.html) to this guide.

**Comment by gkwan-ibm** [comment]
close
- added the link of [Using Docker containers to develop microservices](https://openliberty.io/guides/docker.html) to this guide.
