### ISSUE TITLE
Update the kernel-slim and full image recommendations

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/guide-containerize#150]
The guide includes the following statements that could be interpreted as use 'full' for development and 'kernel-slim' in production, which isn't dev/prod parity.  

"full images are recommended for development only because they significantly expand the image size with features that are not required by the application."

"This parent image with the full tag is recommended for development, but while deploying to production it is recommended to use a parent image with the kernel-slim tag. The kernel-slim tag provides a bare minimum Liberty runtime with the ability to add the features required by the application."

Open Liberty doc includes the following:
"Two different image types are available: kernel-slim or full. The full type provides a server with all Open Liberty features and packages installed.

The kernel-slim type provides just the bare minimum server, which you can customize by adding only the features that your application needs. This image type supports the best practice for production images because you end up with a more lightweight image that packages only what is essential for your application. "

We should change the wording and the placement of the text in the guide so that it's clear we recommend using kernel-slim, but don't mean use full for development and switch to kernel-slim in production

**Comment by leochr** [comment]
@gkwan-ibm just wanted to make sure this is on your radar to address. Thank you

**Comment by gkwan-ibm** [comment]
- most of Dockerfile in the guides are using kernel-slim
- some guides are using full
- 2 guides are deprecated and won't be updated
- only one guide will be updated to  kernel-slim soon.

**Comment by gkwan-ibm** [comment]
close
- all guides were updated except liberty-deep-dive, liberty-deep-dive-gradle, and spring-boot
