### ISSUE TITLE
Feedback from Emily

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-containerize#64]
1. Please add this link for ubi images https://hub.docker.com/r/openliberty/open-liberty/ in this sentence
You can find all the [official images](https://hub.docker.com/_/open-liberty) and [ubi images](https://hub.docker.com/r/openliberty/open-liberty/) at open-liberty Docker Hubs.

1. I don't think the following line is necessary as docker build will automatically does `docker pull` to download the images

**Comment by yeekangc** [comment]
@griffinhadfield, can you see if you can incorporate the above into what you are working on?

Cc @gkwan-ibm

**Comment by griffinhadfield** [comment]
Thank you for the feedback @Emily-Jiang! @yeekangc I will get started on addressing it.

**Comment by gkwan-ibm** [comment]
@Emily-Jiang It is by purpose that having the `docker pull` instruction to enforce the readers to get the latest image. We/readers encountered  problem because the downloaded image was not the latest in local.

**Comment by Emily-Jiang** [comment]
@gkwan-ibm 

> @Emily-Jiang It is by purpose that having the `docker pull` instruction to enforce the readers to get the latest image. We/readers encountered problem because the downloaded image was not the latest in local.

It should get the latest image as the tag is unique for different image.

**Comment by gkwan-ibm** [comment]
@Emily-Jiang we are using `FROM openliberty/open-liberty:kernel-java8-openj9-ubi` which is recommended by the docker team. Do you suggest to use `openliberty/open-liberty:latest`? In our experience, `openliberty/open-liberty:latest` cannot guarantee to always download the latest (unless I missed something)

**Comment by Emily-Jiang** [comment]
@gkwan-ibm I am not suggesting changing the docker image. What you have there is fine. My comment is about not to do extra docker pull as when you use `docker build`, it will do `docker pull` to download the base image. My comment of `latest` is on your comment below. What I meant the `docker build` will download the `from` image just fine.

> @Emily-Jiang It is by purpose that having the `docker pull` instruction to enforce the readers to get the latest image. We/readers encountered problem because the downloaded image was not the latest in local.

I don't think the above statement is true though. Please feel free to double check with docker team.

**Comment by gkwan-ibm** [comment]
A reason to ask users to do `docker pull` that, if not do, it will slow down `liberty:devc` or MST to cause them timeout.

**Comment by gkwan-ibm** [comment]
close
- this issue was addressed
